_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 1
                - 2
                - 3
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
batch_size:
    value: 128
data_dir:
    value: ./nih_data
device:
    value: cuda
epochs:
    value: 1
learning_rate:
    value: 0.01
model:
    value: DenseNet
num_workers:
    value: 8
seed:
    value: 42
wandb_project:
    value: X-Ray Classification
